FROM node:8.11.4-stretch
MAINTAINER asi@dbca.wa.gov.au

RUN apt-get update -y  && apt-get install -y python-pip

WORKDIR /usr/src/app

COPY requirements.txt  ./
COPY gokart ./gokart
COPY dist/dev/sss.* ./dist/dev/
COPY dist/dev/vendor.* ./dist/dev/
COPY dist/release/static ./dist/release/static
COPY node_modules ./node_modules
COPY uwsgi_dev.ini  ./uwsgi.ini

RUN ln -s /usr/src/app/dist/release/static /usr/src/app/dist/dev/static

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080
CMD ["uwsgi", "-i", "uwsgi.ini"]
